### ISSUE TITLE
Jest and Apache Http Client 4.4 error

### ISSUE THREAD

**Issue by swampie** [searchbox-io/Jest#189]
Hello Jest Developers,

we are happily using Jest in our project but since we migrated to 0.1.5 (we were using 0.1.2 before) we are seeing a lot of stack trace like the one below

```
org.apache.http.NoHttpResponseException:EDITED... failed to respond
! at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143) ~[api-0.1-SNAPSHOT-all.jar:0.1]
! at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57) ~[api-0.1-SNAPSHOT-all.jar:0.1]
! at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261) ~[api-0.1-SNAPSHOT-all.jar:0.1]
! at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165) ~[api-0.1-SNAPSHOT-all.jar:0.1]
! at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167) ~[api-0.1-SNAPSHOT-all.jar:0.1]
! at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272) ~[api-0.1-SNAPSHOT-all.jar:0.1]
! at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124) ~[api-0.1-SNAPSHOT-all.jar:0.1]
! at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271) ~[api-0.1-SNAPSHOT-all.jar:0.1]
```

The error happens only when connecting to a remote provider (we tried two so far, one of them is searchly) and the only info I can find about the error is this SO answer

http://stackoverflow.com/questions/21818242/with-httpclient-4-3-x-executing-a-httphead-for-a-specific-url-gives-nohttprespo

which I think is not valid as Jest 0.1.5 is using HttpClient 4.4.

Do you have any past experience about this error? 
Thanks

**Comment by ferhatsb** [comment]
So far I have not a valid test environment to create that issue but it feels like Jest is trying to use a connection which is already closed by server.

Stale checks are disabled with recent versions of Apache Http client due to performance penalty and that may lead this issue happen.( Not sure tbh).

Anyway we have a idle connection reaper to remove idle connections within a given time so these connections won't be used by client in case they are already closed at server side.

Please set .maxConnectionIdleTime(10, TimeUnit.SECONDS) at (10 seconds has no scientific measurement) at HttpClientConfig.

Please share results if this helped any.

**Comment by swampie** [comment]
I will try and let you know

**Comment by kramer** [comment]
Looks like this was a bug in HC4.4 ([HTTPCLIENT-1609](https://issues.apache.org/jira/browse/HTTPCLIENT-1609), [HTTPCLIENT-1610](https://issues.apache.org/jira/browse/HTTPCLIENT-1610)) and is fixed in v4.4.1 to which we'll be upgrading to in Jest's next version.

Closing this issue as I believe it is resolved, please feel free to reopen if you have anymore questions.

**Comment by maksimu** [comment]
I've updated to the most current version of Jest and I see that my code uses HttpClient v4.4.1 but I'm still getting the same error:

```
[web0] 2015-10-08 16:11:07.497 ERROR 124 --- [nio-3000-exec-7] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
[web0] org.apache.http.NoHttpResponseException: db-shared-epsilon-1207.myserverhere.com:4166 failed to respond
[web0] 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143) ~[httpclient-4.5.jar!/:4.5]
[web0] 	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57) ~[httpclient-4.5.jar!/:4.5]
[web0] 	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261) ~[httpcore-4.4.1.jar!/:4.4.1]
[web0] 	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165) ~[httpcore-4.4.1.jar!/:4.4.1]
[web0] 	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272) ~[httpcore-4.4.1.jar!/:4.4.1]
[web0] 	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124) ~[httpcore-4.4.1.jar!/:4.4.1]
[web0] 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271) ~[httpclient-4.5.jar!/:4.5]
[web0] 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[httpclient-4.5.jar!/:4.5]
[web0] 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[httpclient-4.5.jar!/:4.5]
[web0] 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.jar!/:4.5]
[web0] 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[httpclient-4.5.jar!/:4.5]
[web0] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[httpclient-4.5.jar!/:4.5]
[web0] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107) ~[httpclient-4.5.jar!/:4.5]
[web0] 	at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:50) ~[jest-0.1.7.jar!/:na]
[web0] 	at com.company.resources.search.service.SearchIndexerContactsDocESService.search(SearchIndexerContactsDocESService.java:200) ~[ge-0.0.1.jar!/:0.0.1]

```

**Comment by cwei-bgl** [comment]
@ferhatsb set .maxConnectionIdleTime(10, TimeUnit.SECONDS) does solve my problem for now. May need a kind of https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/client/IdleConnectionEvictor.html to check expired connections periodically?
